name: roshan_io
description: "CodeNetra-AI: An accessibility Super-App powering vision-to-voice assistance using Google Gemini 3 Flash"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

  # Fonts & State Management
  google_fonts: ^8.0.0
  provider: ^6.1.2

  # Network & AI
  http: ^1.2.0
  google_generative_ai: ^0.4.7

  # Firebase
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2

  # Voice, Files & Utilities
  flutter_tts: ^4.2.5
  speech_to_text: ^7.3.0
  file_picker: ^10.3.8
  permission_handler: ^12.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  path: ^1.9.0
  camera: ^0.11.3
  syncfusion_flutter_pdf: ^32.1.23
  url_launcher: ^6.2.1
  archive: ^4.0.7
  firebase_ai: ^3.7.0
  flutter_animate: ^4.5.2
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Icon Generator Package
  flutter_launcher_icons: ^0.13.1

# Icon Configuration (FIXED for Android Only) 👇
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false 
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/orb.gif
    - assets/icon.png
